name: warframe_repository
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.9.0

resolution: workspace

dependencies:
  collection: ^1.19.1
  http: ^1.5.0
  http_client:
    path: ../http_client
  warframe_drop_data:
    git:
      url: https://github.com/SlayerOrnstein/wfcd_dart.git
      path: packages/warframe_drop_data
      ref: acbac173e92d4d999921d4b3ab8fa01ee578cc4c
  worldstate_models:
    git:
      url: https://github.com/SlayerOrnstein/wfcd_dart.git
      path: packages/worldstate_models
      ref: acbac173e92d4d999921d4b3ab8fa01ee578cc4c

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.26.2
  very_good_analysis: ^10.0.0
