name: warframe_repository
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.10.0

resolution: workspace

dependencies:
  cache:
    path: ../cache
  collection: ^1.19.1
  http: ^1.5.0
  http_client:
    path: ../http_client
  logging: ^1.3.0
  meta: ^1.17.0
  warframe_drop_data:
    git:
      url: https://github.com/SlayerOrnstein/wfcd_dart.git
      path: packages/warframe_drop_data
      ref: warframe_drop_data-v0.1.5
  worldstate_models:
    git:
      url: https://github.com/SlayerOrnstein/wfcd_dart.git
      path: packages/worldstate_models
      ref: worldstate_models-v0.1.2+1

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.26.2
  very_good_analysis: ^10.0.0
