name: navis_codex
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.10.0
  flutter: ^3.38.0

resolution: workspace

dependencies:
  drift: ^2.30.1
  drift_flutter: ^0.2.8
  flutter:
    sdk: flutter
  http: ^1.6.0
  json_annotation: ^4.9.0
  logging: ^1.3.0
  navis_cache:
    path: ../navis_cache
  path_provider: ^2.1.5
  profile_models:
    git:
      url: https://github.com/SlayerOrnstein/wfcd_dart.git
      path: packages/profile_models
      ref: profile_models-v0.1.2+10
  sentry_drift: ^9.10.0
  warframe_repository:
    path: ../warframe_repository
  warframestat_client: ^5.4.3

dev_dependencies:
  build_runner: ^2.10.5
  drift_dev: ^2.30.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.11.2
  mocktail: ^1.0.4
