name: notification_repository
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.10.0
  flutter: ^3.38.0

resolution: workspace

dependencies:
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4
  flutter:
    sdk: flutter
  intl: ^0.20.1
  warframestat_client: ^5.3.4
