name: wfcd_client
description: Simple wrapper for worldstate api and maybe other WFCD APIs.
version: 2.2.0
author: Ludwig <blacklightinglr@gmail.com>

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  worldstate_api_model:
    path: ../worldstate_model
  warframe_items_model:
    path: ../warframe_items_model
  equatable: ^1.0.1
  dartx: ^0.3.0
  hive: ^1.4.1+1

dev_dependencies:
  test: ^1.6.0
  extra_pedantic: ^1.1.1+3
  mockito: ^4.1.1
