name: navis_ui
description: A Very Good Project created by Very Good CLI.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.10.0
  flutter: ^3.38.0

resolution: workspace

dependencies:
  animated_glitch: ^2.0.0+2
  black_hole_flutter: ^1.0.1
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  flutter_custom_tabs: ^2.4.0
  gap: ^3.0.1
  html: ^0.15.6
  intl: ^0.20.2
  meta: ^1.17.0
  visibility_detector: ^0.4.0+2
  warframe_icons:
    git: https://github.com/SlayerOrnstein/warframe_icons.git

flutter:
  uses-material-design: true
  assets:
    - assets/Derelict.webp
  shaders:
    - "packages/animated_glitch/shader/glitch.frag"

flutter_gen:
  assets:
    outputs:
      package_parameter_enabled: true
