name: warframestat_repository
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.10.0

resolution: workspace

dependencies:
  collection: ^1.18.0
  crypto: ^3.0.6
  equatable: ^2.0.7
  http: ^1.6.0
  http_client:
    path: ../http_client
  json_annotation: ^4.9.0
  logging: ^1.3.0
  navis_cache:
    path: ../navis_cache
  warframestat_client: ^5.3.4
  web_socket_client: ^0.2.1

dev_dependencies:
  build_runner: ^2.7.1
  hive_ce: ^2.11.3
  json_serializable: ^6.10.0
  mocktail: ^1.0.3
  path: ^1.9.0
