name: codex
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.10.0

resolution: workspace

dependencies:
  collection: ^1.19.1
  crypto: ^3.0.6
  http: ^1.6.0
  isar_community: ^3.3.0
  json_annotation: ^4.9.0
  logging: ^1.3.0
  profile_models:
    git:
      url: https://github.com/SlayerOrnstein/wfcd_dart.git
      path: packages/profile_models
      ref: profile_models-v0.1.2+4
  warframestat_client: ^5.3.4

dev_dependencies:
  build_runner: ^2.7.1
  isar_community_generator: ^3.3.0
  json_serializable: ^6.11.1
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0
